version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python-development:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    groups:
      website:
        patterns: ['*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
